run:
  timeout: 5m
  tests: true
  concurrency: 4
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - misspell
    - bodyclose
    - gocritic
    - gosec
    - nakedret
    - contextcheck
    - goconst
    - nilerr
    - noctx
    - unconvert
    - unparam
    - whitespace
    - prealloc
    - durationcheck
    - errorlint
    - reassign
    - thelper
    - tparallel

linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow

  errcheck:
    check-type-assertions: true
    check-blank: true

  goconst:
    min-occurrences: 4

  gocritic:
    enabled-tags:
      - performance
      - diagnostic
      - style

  gosec:
    excludes:
      - G104  # Allow unchecked errors in some cases

  misspell:
    locale: US

  nakedret:
    max-func-lines: 30

  whitespace:
    multi-if: false
    multi-func: false

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true

output:
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
