version: 2

run:
  timeout: 5m
  tests: true
  concurrency: 4

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - revive
    - ineffassign
    - unused
    - misspell
    - bodyclose
    - gocritic
    - makezero
    - gosec
    - nakedret
    - contextcheck
    - goconst
    - godot
    - goprintffuncname
    - nilerr
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - unparam
    - whitespace

output:
  print-issued-lines: true
  print-linter-name: true
